version: "3"
services:
  web-app:
    container_name: web-app
    image: registry.cn-heyuan.aliyuncs.com/coding_01/creative-ai-hub-web:1.8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_HOST=http://localhost:8090
    volumes:
      - ./data:/app/data
    networks:
      - 1panel-network

  api-app:
    container_name: api-app
    image: registry.cn-heyuan.aliyuncs.com/coding_01/creative-ai-hub-data:1.8
    ports:
      - "8090:8090"
    environment:
      CROSS_ORIGIN: "https://ai.kangyaocoding.top"
      WHITE_LIST: o3Ez96fFWNn7v9bGnjr-vfEQUh0o
      GPT_API_HOST: https://4.0.wokaai.com/
      GPT_API_KEY: sk-Z2hKcfFVaJ3hfv3LC813BdD351A34aA59bA145Bc2aE9BbE2
      GLM_API_HOST: https://open.bigmodel.cn/
      GLM_API_KEY: 240330a3f5aedcc641921f1706835d12.8desNYHII4ZWTQNt
      WX_MCH_ID: 1676819850
      WX_SECRET_KEY: 6d50fba3afd64e18389987edd2776822
      WX_NOTIFY_URL: https://ai.kangyaocoding.top/api/v1/sale/pay_notify
      DB_USERNAME: potter
      DB_PASSWORD: mysql_05lky01
      DB_URL: jdbc:mysql://47.113.199.200:3306/openai?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      SECRET_KEY: FeaQOE8TPnMT4rka+hW0lGFguV15aMPhWRm3NuNBz6U=
      WECHAT_ORIGINAL_ID: gh_a03f1e42e9cb
      WECHAT_APP_ID: wx1cf2d2b7cdbfaa99
      WECHAT_TOKEN: Lcorw8oZruRZ6cYXLQ5
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
